apiVersion: v1
kind: Service
metadata:
  name: rekkids-service
  labels:
    app: rekkids
spec:
  ports:
    - name: http-rekkids
      port: 4000
  selector:
    app: rekkids
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekkids
  labels:
    app: rekkids
spec:
  selector:
    matchLabels:
      app: rekkids
  template:
    metadata:
      labels:
        app: rekkids
    spec:
      containers:
        - name: rekkids
          image: rekkids-image
          ports:
            - containerPort: 4000
        - name: opa
          image: openpolicyagent/opa:0.40.0-envoy-rootless
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config-vol
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5      # Tune these periods for your environemnt
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true  # Include bundle activation in readiness
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          args:
          - "run"
          - "--server"
          - "--ignore=.*"
          - "--config-file=/config/conf.yaml"
          - "--authorization=basic"
          - "--addr=http://127.0.0.1:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
      volumes:
        - name: opa-config-vol
          configMap:
            name: opa-istio-config
